src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="date")
     */
    private $DateSortie;

    /**
     * @ORM\OneToOne(targetEntity=Images::class, mappedBy="IdFilm", cascade={"persist", "remove"})
     */
    private $images;

    /**
     * @ORM\OneToOne(targetEntity=Videos::class, mappedBy="idFilm", cascade={"persist", "remove"})
     */
    private $videos;

    /**
     * @ORM\OneToMany(targetEntity=Avis::class, mappedBy="idFilm", orphanRemoval=true)
     */
    private $avis;

    /**
     * @ORM\Column(type="date")
     */
    private $DateMinDiffusion;

    /**
     * @ORM\Column(type="date")
     */
    private $DateMaxDiffusion;

    /**
     * @ORM\ManyToMany(targetEntity=Tags::class, inversedBy="films")
     */
    private $Tags;




    public function __construct()
    {
        $this->seances = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->Tag = new ArrayCollection();
        $this->Tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->DateSortie;
    }

    public function setDateSortie(\DateTimeInterface $DateSortie): self
    {
        $this->DateSortie = $DateSortie;

        return $this;
    }

    /**
     * @return Collection|Seance[]
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }

    public function addSeance(Seance $seance): self
    {
        if (!$this->seances->contains($seance)) {
            $this->seances[] = $seance;
            $seance->setNomFilm($this);
        }

        return $this;
    }

    public function removeSeance(Seance $seance): self
    {
        if ($this->seances->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getNomFilm() === $this) {
                $seance->setNomFilm(null);
            }
        }

        return $this;
    }

    public function getImages(): ?Images
    {
        return $this->images;
    }

    public function setImages(Images $images): self
    {
        // set the owning side of the relation if necessary
        if ($images->getIdFilm() !== $this) {
            $images->setIdFilm($this);
        }

        $this->images = $images;

        return $this;
    }

    public function getVideos(): ?Videos
    {
        return $this->videos;
    }

    public function setVideos(Videos $videos): self
    {
        // set the owning side of the relation if necessary
        if ($videos->getIdFilm() !== $this) {
            $videos->setIdFilm($this);
        }

        $this->videos = $videos;

        return $this;
    }

    /**
     * @return Collection|Avis[]
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis[] = $avi;
            $avi->setIdFilm($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): self
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getIdFilm() === $this) {
                $avi->setIdFilm(null);
            }
        }

        return $this;
    }

    public function getDateMinDiffusion(): ?\DateTimeInterface
    {
        return $this->DateMinDiffusion;
    }

    public function setDateMinDiffusion(\DateTimeInterface $DateMinDiffusion): self
    {
        $this->DateMinDiffusion = $DateMinDiffusion;

        return $this;
    }

    public function getDateMaxDiffusion(): ?\DateTimeInterface
    {
        return $this->DateMaxDiffusion;
    }

    public function setDateMaxDiffusion(\DateTimeInterface $DateMaxDiffusion): self
    {
        $this->DateMaxDiffusion = $DateMaxDiffusion;

        return $this;
    }

    /**
     * @return Collection|Tags[]
     */
    public function getTags(): Collection
    {
        return $this->Tags;
    }

    public function addTag(Tags $tag): self
    {
        if (!$this->Tags->contains($tag)) {
            $this->Tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tags $tag): self
    {
        $this->Tags->removeElement($tag);

        return $this;
    }

    public function __toString()
    {
        return $this->Nom;
    }


}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Seance::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $idFilm;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $idUser;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbrPlaces;

    /**
     * @ORM\Column(type="integer")
     */
    private $Etat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateCreation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdFilm(): ?Seance
    {
        return $this->idFilm;
    }

    public function setIdFilm(?Seance $idFilm): self
    {
        $this->idFilm = $idFilm;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->idUser;
    }

    public function setIdUser(?User $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getNbrPlaces(): ?int
    {
        return $this->NbrPlaces;
    }

    public function setNbrPlaces(int $NbrPlaces): self
    {
        $this->NbrPlaces = $NbrPlaces;

        return $this;
    }

    public function getEtat(): ?int
    {
        return $this->Etat;
    }

    public function setEtat(int $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function __construct()
    {
        $this->Etat = 1;
        $this->DateCreation = new \DateTime();
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use App\Entity\Seance;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('NbrPlaces', IntegerType::class,[
                'label' => 'Nombre de place(s)'
            ])
            ->add('idFilm', EntityType::class,[
                'label' => 'Seance ',
                'class' => Seance::class,
                'choice_label' => 'id'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
            'csrf_protection' => false,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\User;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use PhpParser\Node\Expr\Empty_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Dompdf\Dompdf;
use Dompdf\Options;

class ReservationController extends AbstractController
{

    /**
     * @Route("/reservation/{idreservation}/export", name="reservation_export")
     */
    public function export(ReservationRepository $reservationRepository, $idreservation)
    {
        $pdfOptions = new Options();
        $pdfOptions->setDefaultFont('Arial');
        $pdfOptions->setIsRemoteEnabled(true);
        $dompdf = new Dompdf($pdfOptions);
        $context = stream_context_create(
            [
                'ssl' => [
                    'verify_peer' => FALSE,
                    'verify_peer_name' => FALSE,
                    'allow_self_signed'=> TRUE
                ]
            ]
        );
        $dompdf->setHttpContext($context);

        $html = $this->render('reservation/export.html.twig', [
            'reservations' => $reservationRepository->findBy(
                ['id' => $idreservation]
            ),
        ]);
        $dompdf->loadHtml($html->getContent());
        $dompdf->setPaper('A4','portrait');
        $dompdf->render();

        $fichier = 'billet-'.$this->getUser()->getNom().'-'.$this->getUser()->getPrenom().'-'.'.pdf';

        $dompdf->stream($fichier, [
            'Attachment' => true
        ]);

        return new Response();
    }

    /**
     * @Route("/moderateur/reservation/{idreservation}/valider", name="reservation_valider")
     * @param ReservationRepository $reservationRepository
     * @param $idreservation
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function valider(ReservationRepository  $reservationRepository, $idreservation)
    {
         $reservationRepository->valider($idreservation);
        return $this->redirectToRoute('reservation_index');
    }

    /**
     * @Route("/{idreservation}/{idseance}/{nbr}/cancel", name="reservation_cancel", methods={"GET","POST"})
     */
    public function cancel(ReservationRepository $reservationRepository, $idseance, $idreservation, $nbr)
    {
        $reservationRepository->cancel($idseance, $nbr, $idreservation);
        return $this->redirectToRoute('accueil');
    }

    /**
     * @Route("/consult", name="reservation_consult")
     * @param ReservationRepository $reservationRepository
     * @return Response
     */
    public function consult(ReservationRepository $reservationRepository, Security $security): Response
    {
        $date = new \DateTime();
        $user = new User();
        $user = $security->getUser();
        return $this->render('reservation/consult.html.twig',[
            'reservations' => $reservationRepository->findBy(
            ['idUser'=> $user]
            ),
            'date'=> $date,
        ]);
    }

    /**
     * @Route("/moderateur/reservation/actions", name="reservation_actions")
     * @param ReservationRepository $reservationRepository
     * @return Response
     */
    public function action(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/actions.html.twig',[
            'reservations' => $reservationRepository->findBy(
                ['Etat' => 1]
            )
    ]);
    }

    /**
     * @Route("/moderateur/reservation/validées", name="reservation_index", methods={"GET"})
     */
    public function valid(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findBy(
                ['Etat' => 0]
            ),
        ]);
    }

    /**
     * @Route("/moderateur/reservation/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request, Security $security): Response
    {
        $utilisateur = new User();
        $utilisateur = $security->getUser();
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $reservation->setIdUser($utilisateur);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();
            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/moderateur/reservation/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/moderateur/reservation/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/moderateur/reservation/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }


}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/actions.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <table class="table table-striped table-dark" style="text-align: center">
        <thead>
        <tr>
            <th colspan="11"><h1>Reservations actives</h1></th>
        </tr>
        <tr>
            <th>Id reservation</th>
            <th>Id seance</th>
            <th>Nom</th>
            <th>Nombres de places réservés</th>
            <th>Numero salle</th>
            <th>Date de la séance</th>
            <th>Email</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Actions sur la reservation</th>
            <th>Statut de la reservation</th>
        </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            {% if "now"|date('U') > reservation.idFilm.heure|date('U') or reservation.Etat == 2%}

            {% else %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.idFilm.id }}</td>
                    <td>{{ reservation.idFilm.idFilm.Nom }}</td>
                    <td>{{ reservation.NbrPlaces }}</td>
                    <td>{{ reservation.idFilm.idSalle.Numero }}</td>
                    <td>{{ reservation.idFilm.heure|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY à HH:mm:ss")  }}</td>
                    <td>{{ reservation.idUser.email }}</td>
                    <td>{{ reservation.idUser.nom }}</td>
                    <td>{{ reservation.idUser.prenom }}</td>
                    <td>
                        {% if reservation.Etat == 0 %}
                            <a class="btn btn-danger btn-sm" href="{{ path('reservation_cancel', {'idreservation': reservation.id, 'idseance': reservation.idFilm.id, 'nbr': reservation.NbrPlaces}) }}">Annuler</a>
                        {% else %}
                            <a class="btn btn-danger btn-sm" href="{{ path('reservation_cancel', {'idreservation': reservation.id, 'idseance': reservation.idFilm.id, 'nbr': reservation.NbrPlaces}) }}">Annuler</a>
                            <a class="btn btn-success btn-sm" href="{{ path('reservation_valider',{'idreservation': reservation.id}) }}">Valider</a>
                        {% endif%}
                    </td>
                    <td>
                        {% if reservation.Etat == 0 %}
                            <span class="badge badge-pill badge-success">Reservé</span>
                        {% elseif reservation.Etat == 1 %}
                            <span class="badge badge-pill badge-warning">En cours de validation</span>
                        {% else %}
                            <span class="badge badge-pill badge-danger">Annulé</span>
                        {% endif %}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/reservation/consult.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes reservations{% endblock %}

{% block body %}
    <body>
    <div>
        <table class="table table-striped table-dark" style="text-align: center">
        <thead>
        <tr>
            <th colspan="10" style="text-align: center">
                <h1>Mes reservations</h1>
            </th>
        </tr>
            <tr>
                <th>Nom</th>
                <th>Nombres de places réservés</th>
                <th>Numero salle</th>
                <th>Date de la séance</th>
                <th>Email</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Horaire de la reservation</th>
                <th>Actions sur la reservation</th>
                <th>Statut de la reservation</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            {% if "now"|date('U') <= reservation.idFilm.heure|date('U')  %}
                <tr>
                    <td>{{ reservation.idFilm.idFilm.Nom }}</td>
                    <td>{{ reservation.NbrPlaces }}</td>
                    <td> {{ reservation.idFilm.idSalle.Numero }}</td>
                    <td> {{ reservation.idFilm.heure|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY à HH:mm:ss")  }}</td>
                    <td>{{ reservation.idUser.email }}</td>
                    <td>{{ reservation.idUser.nom }}</td>
                    <td>{{ reservation.idUser.prenom }}</td>
                    <td>{{ reservation.DateCreation|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY à HH:mm:ss")  }}</td>
                    <td>
                        {% if reservation.Etat == 2 %}

                        {% else %}
                            <a class="btn btn-danger btn-sm" href="{{ path('reservation_cancel', {'idreservation': reservation.id, 'idseance': reservation.idFilm.id, 'nbr': reservation.NbrPlaces}) }}">Annuler</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if reservation.Etat == 0 %}
                            <span class="badge badge-pill badge-success">Reservé</span>
                            <a title="Imprimer votre billet en ligne" href="{{ path('reservation_export', {'idreservation': reservation.id}) }}"><img style="width: 30px; margin-left: 20px" src="{{ asset('images/print-solid.svg') }}" alt="Imprimer vottre billet"></a>
                        {% elseif reservation.Etat == 1 %}
                            <span class="badge badge-pill badge-warning">En cours de validation</span>
                        {% else %}
                            <span class="badge badge-pill badge-danger">Annulé</span>
                        {% endif %}
                    </td>
                </tr>
            {% else %}

            {% endif %}
        {% endfor %}
        </tbody>
        </table>
    </div>
    </body>
{% endblock %}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/export.html.twig
{% block body %}
    <div style="position: fixed">
        <h1 style="text-align: center">Reservation</h1>
    </div>
    {% for reservation in reservations %}
{#        <img src="{{ asset('/images/ticket.png') }}">#}
{#        <img style="width: 400px; height: 400px" src="{{ reservation.idFilm.idFilm.Image }}">#}
        <img style="width: 90%; position: fixed; margin-left: 5%; margin-right: 5%;" src="{{ absolute_url(asset('images/ticket.png')) }}">
        <div style="width: 88%;height: 40%;margin-left: 15%; margin-right: 5%; margin-top: 15%; ">
            <div id="film" style="width: 50%;">
                <p style="font-family: 'Roboto', monospace;"> Date de sortie du film : {{ reservation.idFilm.idFilm.DateSortie|date("Y-m")  }}</p>
                <p style="font-family: 'Roboto', monospace;"> Nom du film : {{ reservation.idFilm.idFilm.Nom }}</p>
            </div>
            <div id="code" style="width: auto;margin-left: 90px;margin-top: 4%; float:right; text-align: center">
                <img style="width: 300px; transform: rotate(90deg)" src="{{ absolute_url(asset('images/code.png')) }}">
            </div>
            <div id="reserv" style="width:50%;float: left">
                {% if reservation.NbrPlaces == 1 %}
                    <p style="font-family: 'Roboto', monospace;">{{ reservation.NbrPlaces }} place</p>
                {% else %}
                    <p style="font-family: 'Roboto', monospace;"> {{ reservation.NbrPlaces }} places</p>
                {% endif %}
                    <p style="font-family: 'Roboto', monospace;"> Séance:{{ reservation.idFilm.heure|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY à HH:mm")}}</p>
                    <p style="font-family: 'Roboto', monospace;"> {{ reservation.idUser.Nom }} {{ reservation.idUser.Prenom }}</p>
            </div>
        </div>

    {% endfor %}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes reservations{% endblock %}

{% block body %}
    <table class="table table-striped table-dark" style="text-align: center">
        <thead>
        <tr>
            <th colspan="11"><h1>Reservations actives</h1></th>
        </tr>
            <tr>
                <th>Id reservation</th>
                <th>Id seance</th>
                <th>Nom</th>
                <th>Nombres de places réservés</th>
                <th>Numero salle</th>
                <th>Date de la séance</th>
                <th>Email</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Actions sur la reservation</th>
                <th>Statut de la reservation</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            {% if "now"|date('U') > reservation.idFilm.heure|date('U') or reservation.Etat == 2%}

        {% else %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.idFilm.id }}</td>
                <td>{{ reservation.idFilm.idFilm.Nom }}</td>
                <td>{{ reservation.NbrPlaces }}</td>
                <td>{{ reservation.idFilm.idSalle.Numero }}</td>
                <td>{{ reservation.idFilm.heure|format_datetime(locale='fr',pattern="EEEE dd MMMM YYYY à HH:mm:ss")  }}</td>
                <td>{{ reservation.idUser.email }}</td>
                <td>{{ reservation.idUser.nom }}</td>
                <td>{{ reservation.idUser.prenom }}</td>
                <td>
                    {% if reservation.Etat == 0 %}
                        <a class="btn btn-danger btn-sm" href="{{ path('reservation_cancel', {'idreservation': reservation.id, 'idseance': reservation.idFilm.id, 'nbr': reservation.NbrPlaces}) }}">Annuler</a>
                    {% else %}
                        <a class="btn btn-danger btn-sm" href="{{ path('reservation_cancel', {'idreservation': reservation.id, 'idseance': reservation.idFilm.id, 'nbr': reservation.NbrPlaces}) }}">Annuler</a>
                        <a class="btn btn-success btn-sm" href="{{ path('reservation_valider',{'idreservation': reservation.id}) }}">Valider</a>
                    {% endif%}
                </td>
                <td>
                    {% if reservation.Etat == 0 %}
                        <span class="badge badge-pill badge-success">Reservé</span>
                    {% elseif reservation.Etat == 1 %}
                        <span class="badge badge-pill badge-warning">En cours de validation</span>
                    {% else %}
                        <span class="badge badge-pill badge-danger">Annulé</span>
                    {% endif %}</td>
            </tr>
        {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('reservation_index') }}">back to list</a>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>NbrPlaces</th>
                <td>{{ reservation.NbrPlaces }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}