src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AvisRepository::class)
 */
class Avis
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Film::class, inversedBy="avis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idFilm;

    /**
     * @ORM\Column(type="text")
     */
    private $Avis;


    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="integer")
     */
    private $Note;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="avis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idUser;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdFilm(): ?Film
    {
        return $this->idFilm;
    }

    public function setIdFilm(?Film $idFilm): self
    {
        $this->idFilm = $idFilm;

        return $this;
    }

    public function getAvis(): ?string
    {
        return $this->Avis;
    }

    public function setAvis(string $Avis): self
    {
        $this->Avis = $Avis;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->idUser;
    }

    public function setIdUser(User $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->Note;
    }

    public function setNote(int $Note): self
    {
        $this->Note = $Note;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function __construct()
    {
        $this->setVisible(0);
    }
}

src/Form/AvisType.php
<?php

namespace App\Form;

use App\Entity\Avis;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Avis', TextType::class,
            [
                'label' => false
            ])
            ->add('Note',ChoiceType::class,
                ['choices' =>
                    [
                        1=>1,
                        2=>2,
                        3=>3,
                        4=>4,
                        5=>5
                    ]
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Avis::class,
        ]);
    }
}

src/Controller/AvisController.php
<?php

namespace App\Controller;

use App\Entity\Avis;
use App\Entity\Film;
use App\Entity\User;
use App\Form\AvisType;
use App\Repository\AvisRepository;
use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/avis")
 */
class AvisController extends AbstractController
{
    /**
     * @Route("/{id}/cancel", name="avis_remove")
     * @param $id
     * @param AvisRepository $avisRepository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function supprimer($id, AvisRepository $avisRepository)
    {
        $avis = $avisRepository->findOneBy(
            [
                'id' => $id
            ]
        );
        $em = $this->getDoctrine()->getManager();
        $em->remove($avis);
        $em->flush();
        return $this->redirectToRoute('accueil');
    }
    /**
     * @Route("/{id}/confirm", name="avis_confirm")
     * @param $idavis
     * @param AvisRepository $avisRepository
     */
    public function confirmer($id, AvisRepository $avisRepository)
    {
        $avis = $avisRepository->findOneBy([
            'id' => $id
            ]
        );

        $avis->setVisible(1);
        $em = $this->getDoctrine()->getManager();
        $em->persist($avis);
        $em->flush();
        return $this->redirectToRoute('accueil');
    }
    /**
     * @Route("/", name="avis_index", methods={"GET"})
     */
    public function index(AvisRepository $avisRepository): Response
    {
        return $this->render('avis/index.html.twig', [
            'avis' => $avisRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{idFilm}/new", name="avis_new", methods={"GET","POST"})
     */
    public function new(FilmRepository  $filmRepository, Request $request, Security $security, $idFilm): Response
    {
        $avi = new Avis();
        $user = new User();
        $film = new Film();
        $user = $security->getUser();
        $film = $filmRepository->findOneBy(
            ['id' => $idFilm]
        );
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $avi = $avi->setIdUser($user);
            $avi = $avi->setDateCreation(new \DateTime());
            $avi = $avi->setIdFilm($film);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($avi);
            $entityManager->flush();
            return $this->redirectToRoute('accueil');
        }

        return $this->render('avis/new.html.twig', [
            'avi' => $avi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="avis_show", methods={"GET"})
     */
    public function show(Avis $avi): Response
    {
        return $this->render('avis/show.html.twig', [
            'avi' => $avi,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="avis_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Avis $avi): Response
    {
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('avis_index');
        }

        return $this->render('avis/edit.html.twig', [
            'avi' => $avi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="avis_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Avis $avi): Response
    {
        if ($this->isCsrfTokenValid('delete'.$avi->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($avi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('avis_index');
    }
}

templates/avis/_delete_form.html.twig
<form method="post" action="{{ path('avis_delete', {'id': avi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ avi.id) }}">
    <button class="btn">Delete</button>
</form>

templates/avis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Envoyer') }}</button>
{{ form_end(form) }}

templates/avis/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Avis{% endblock %}

{% block body %}
    <h1>Edit Avis</h1>

    {{ include('avis/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('avis_index') }}">back to list</a>

    {{ include('avis/_delete_form.html.twig') }}
{% endblock %}

templates/avis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis index{% endblock %}

{% block body %}
    <h1>Avis index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Avis</th>
                <th>Date_creation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for avi in avis %}
            <tr>
                <td>{{ avi.id }}</td>
                <td>{{ avi.Avis }}</td>
                <td>{{ avi.dateCreation ? avi.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('avis_show', {'id': avi.id}) }}">show</a>
                    <a href="{{ path('avis_edit', {'id': avi.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('avis_new') }}">Create new</a>
{% endblock %}

templates/avis/new.html.twig
{% block body %}
    <h1>Ajouter un Avis</h1>

    {{ include('avis/_form.html.twig') }}
{% endblock %}

templates/avis/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis{% endblock %}

{% block body %}
    <h1>Avis</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ avi.id }}</td>
            </tr>
            <tr>
                <th>Avis</th>
                <td>{{ avi.Avis }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ avi.dateCreation ? avi.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('avis_index') }}">back to list</a>

    <a href="{{ path('avis_edit', {'id': avi.id}) }}">edit</a>

    {{ include('avis/_delete_form.html.twig') }}
{% endblock %}